import mysql.connector

database = mysql.connector.connect(
    host="localhost",
    user="root",
    password="root",
    database="sample"
)

mycursor = database.cursor()

sql = """
INSERT INTO attractions_api_attraction (name, description, price, rating, date_created, food_description, housing_description, activity_description) 
VALUES 
    ('Paris', 'Paris, the capital city of France, is known worldwide for its art, fashion, gastronomy, and culture. The cityscape is adorned with iconic landmarks such as the Eiffel Tower, Notre-Dame Cathedral, and the Louvre Museum, housing thousands of works of art including the Mona Lisa. Paris is often referred to as the "City of Love" due to its romantic ambiance, charming neighborhoods, and scenic riverbanks along the Seine. Visitors can indulge in exquisite French cuisine at Michelin-starred restaurants or enjoy a leisurely picnic in one of the many picturesque parks. Accommodation options range from luxury hotels with stunning views of the city to cozy boutique guesthouses tucked away in quaint streets.', 300, 0, '2024-03-12', 'French cuisine is celebrated for its rich flavors, elegant presentation, and culinary traditions. Visitors to Paris can savor classic dishes such as coq au vin, boeuf bourguignon, and escargot, paired with fine wines from the renowned vineyards of Bordeaux and Burgundy. Bakeries and patisseries offer an array of freshly baked croissants, baguettes, and pastries that tempt the taste buds.', 'Paris offers a diverse range of accommodation options to suit every traveler''s preference and budget. Luxury hotels such as the Ritz Paris and the Four Seasons Hotel George V provide unparalleled luxury and world-class amenities. Alternatively, charming boutique hotels and cozy bed-and-breakfasts offer a more intimate and personalized experience. Airbnb rentals and serviced apartments are also popular choices for those seeking a home away from home.', 'Paris offers an array of activities and attractions to suit every interest. Art enthusiasts can explore world-class museums such as the Louvre, Musee d''Orsay, and Centre Pompidou. Architecture lovers can admire iconic landmarks such as the Eiffel Tower, Notre-Dame Cathedral, and Sacre-Coeur Basilica. Shopping enthusiasts can stroll along the Champs-Elysees and explore designer boutiques and flagship stores. And for those seeking relaxation, the city''s beautiful parks, gardens, and river cruises provide the perfect escape from the hustle and bustle of urban life.'),
    ('Tokyo', 'Tokyo, the bustling capital of Japan, is a vibrant metropolis that seamlessly blends modernity with tradition. The cityscape is characterized by towering skyscrapers, neon-lit streets, and historic temples and shrines. Tokyo is renowned for its rich cultural heritage, cutting-edge technology, and eclectic cuisine. Visitors can explore traditional neighborhoods such as Asakusa and Shibuya, or immerse themselves in the futuristic districts of Shinjuku and Ginza. With its dynamic energy and endless attractions, Tokyo offers an unforgettable experience for travelers of all ages.', 200, 0, '2024-03-12', 'Tokyo boasts a diverse and exciting culinary scene that caters to every taste and budget. From world-renowned sushi bars and Michelin-starred restaurants to cozy izakayas and street food stalls, the city offers an array of delicious dining options. Visitors can sample traditional Japanese dishes such as sushi, ramen, tempura, and yakitori, as well as international cuisines from around the world.', 'Tokyo offers a wide range of accommodation options to suit every traveler''s needs and budget. Luxury hotels such as the Park Hyatt Tokyo and Mandarin Oriental provide unparalleled luxury and impeccable service, while budget-friendly options such as capsule hotels and guesthouses offer affordable and convenient stays. Airbnb rentals and serviced apartments are also popular choices for those looking for a home away from home.', 'Tokyo offers a wealth of activities and attractions to suit every interest. History buffs can explore ancient temples and shrines such as Senso-ji and Meiji Shrine, while art enthusiasts can visit world-class museums such as the Tokyo National Museum and Mori Art Museum. Shopping enthusiasts can indulge in retail therapy in trendy neighborhoods such as Harajuku and Akihabara, while nature lovers can escape the urban jungle and explore lush parks and gardens such as Ueno Park and Shinjuku Gyoen.'),
    ('New York City', 'New York City, often referred to as the "Big Apple," is one of the most iconic cities in the world. Located in the northeastern United States, NYC is a melting pot of cultures, cuisines, and experiences. The city is famous for its towering skyscrapers, bustling streets, and vibrant neighborhoods, each with its own unique character and charm. From world-class museums and theaters to iconic landmarks and parks, there''s never a dull moment in the city that never sleeps.', 400, 0, '2024-03-12', 'New York City is a food lover''s paradise, offering an endless array of culinary delights from around the world. From classic New York-style pizza and bagels to gourmet burgers and ethnic street food, there''s something to satisfy every craving. Visitors can dine at Michelin-starred restaurants, trendy cafes, and hole-in-the-wall eateries, or grab a quick bite from one of the city''s many food trucks and vendors.', 'New York City offers a wide range of accommodation options to suit every budget and preference. From luxury hotels with skyline views and five-star amenities to budget-friendly hostels and boutique guesthouses, there''s something for every traveler. Airbnb rentals and short-term apartment rentals are also popular choices for those looking for a home away from home.', 'New York City offers an endless array of activities and attractions to suit every interest. Art lovers can explore world-class museums such as the Metropolitan Museum of Art and the Museum of Modern Art, while theater enthusiasts can catch a Broadway show or off-Broadway production. Outdoor enthusiasts can explore Central Park, stroll along the High Line, or take a ferry to the Statue of Liberty and Ellis Island. And with its vibrant nightlife scene, there''s no shortage of bars, clubs, and entertainment venues to keep the party going into the wee hours of the morning.'),
    ('Rome', 'Rome, the capital city of Italy, is a captivating blend of ancient history, Renaissance art, and modern culture. Known as the "Eternal City," Rome is home to iconic landmarks such as the Colosseum, Roman Forum, and Vatican City, as well as world-class museums, art galleries, and bustling piazzas. With its rich heritage, vibrant street life, and delicious cuisine, Rome offers an unforgettable experience for travelers from around the globe.', 250, 0, '2024-03-12', 'Rome is a food lover''s paradise, offering a mouthwatering array of traditional Italian dishes, regional specialties, and international cuisine. From classic pasta dishes like spaghetti carbonara and cacio e pepe to Roman-style pizza and gelato, there''s something to satisfy every palate. Visitors can dine at cozy trattorias, elegant ristorantes, and bustling markets, or enjoy a leisurely picnic in one of the city''s beautiful parks or piazzas.', 'Rome offers a wide range of accommodation options to suit every budget and preference. From luxury hotels and boutique guesthouses to budget-friendly hostels and short-term apartment rentals, there''s something for every traveler. Many hotels are located in the historic center of Rome, within walking distance of major attractions, while others offer stunning views of the city skyline or the Tiber River.', 'Rome offers a wealth of activities and attractions to suit every interest. History buffs can explore ancient ruins such as the Colosseum, Roman Forum, and Pantheon, while art lovers can marvel at masterpieces by Michelangelo, Raphael, and Caravaggio in the city''s museums and galleries. Foodies can indulge in culinary tours, wine tastings, and cooking classes, while outdoor enthusiasts can explore parks, gardens, and scenic viewpoints throughout the city.'),
    ('Sydney', 'Sydney, the capital city of New South Wales, Australia, is a vibrant metropolis known for its stunning harbor, iconic landmarks, and diverse culture. The city is home to world-famous attractions such as the Sydney Opera House, Sydney Harbour Bridge, and Bondi Beach, as well as lush parks, vibrant neighborhoods, and a thriving arts and dining scene. With its beautiful beaches, vibrant street life, and laid-back vibe, Sydney offers something for everyone to enjoy.', 300, 0, '2024-03-12', 'Sydney offers a diverse culinary scene that reflects its multicultural population and coastal location. Visitors can enjoy fresh seafood at waterfront restaurants, sample innovative dishes at award-winning eateries, and savor traditional Australian cuisine at local pubs and cafes. From fish and chips by the beach to fine dining experiences with harbor views, there''s something to suit every taste and budget in Sydney.', 'Sydney offers a wide range of accommodation options to suit every traveler''s needs and budget. From luxury hotels and boutique guesthouses to budget-friendly hostels and short-term apartment rentals, there''s something for every taste and budget. Many hotels are located in the city center, within walking distance of major attractions, while others offer stunning views of the harbor or the beach.', 'Sydney offers a wealth of activities and attractions to suit every interest. Outdoor enthusiasts can surf at Bondi Beach, hike in the Blue Mountains, or take a ferry to Manly Beach. Culture lovers can explore museums, galleries, and historic sites such as the Art Gallery of New South Wales, the Museum of Contemporary Art, and the Sydney Observatory. And with its vibrant nightlife scene, there are plenty of bars, clubs, and live music venues to keep the party going into the night.'),
    ('Santorini, Greece', 'Santorini is a volcanic island in the Cyclades group of the Greek islands. It is famous for its dramatic views, stunning sunsets, and whitewashed buildings.', 400, 0, '2024-03-12', 'Traditional Greek cuisine with fresh ingredients, including moussaka, souvlaki, and Greek salads.', 'Cave houses and luxury hotels built into the cliffs offer breathtaking views of the Aegean Sea.', 'Explore ancient ruins, relax on black sand beaches, and indulge in wine tasting tours.'),
    ('Maui, Hawaii', 'Maui is an island in the Central Pacific, part of the Hawaiian archipelago. It is known for its stunning beaches, lush rainforests, and diverse landscapes.', 350, 0, '2024-03-12', 'Fresh seafood, Hawaiian plate lunches, and tropical fruits like pineapple and coconut.', 'Luxury resorts and beachfront villas offer accommodations with ocean views and access to world-class amenities.', 'Experience snorkeling with sea turtles, hiking through bamboo forests, and watching sunrise at the summit of Haleakalā.'),
    ('Safari in Serengeti National Park, Tanzania', 'Serengeti National Park, located in Tanzania, is renowned for its vast savannahs, diverse wildlife, and annual migration of millions of wildebeest, zebras, and other animals.', 600, 0, '2024-03-12', 'Traditional Tanzanian cuisine featuring grilled meats, stews, and local vegetables.', 'Luxury tented camps and lodges provide comfortable accommodations in the heart of the wilderness.', 'Embark on game drives to spot the Big Five (lion, elephant, buffalo, leopard, and rhinoceros), witness the Great Migration, and explore the parks diverse ecosystems.'),
    ('Kyoto, Japan', 'Kyoto is a city on the island of Honshu in Japan. Its famous for its classical Buddhist temples, as well as gardens, imperial palaces, Shinto shrines, and traditional wooden houses.', 400, 0, '2024-03-12', 'Traditional Japanese cuisine such as sushi, sashimi, and tempura.', 'Ryokans (traditional Japanese inns) offer authentic accommodations with tatami floors and communal baths.', 'Explore historic temples and gardens, participate in tea ceremonies, and experience traditional Japanese arts and crafts.'),
    ('Machu Picchu, Peru', 'Machu Picchu is an ancient Incan citadel set high in the Andes Mountains of Peru. Its renowned for its well-preserved ruins, dramatic landscapes, and panoramic views.', 450, 0, '2024-03-12', 'Peruvian cuisine featuring ceviche, quinoa, and roasted meats.', 'Stay in nearby hotels or lodges in Aguas Calientes, the gateway to Machu Picchu.', 'Explore the ruins of Machu Picchu, hike the Inca Trail, and visit nearby attractions such as the Sacred Valley and Huayna Picchu.'),
    ('Safari in Kruger National Park, South Africa', 'Kruger National Park is one of Africas largest game reserves, known for its abundant wildlife and diverse ecosystems. Its located in northeastern South Africa.', 550, 0, '2024-03-12', 'Traditional South African cuisine such as braai (barbecue), biltong (dried meat), and potjiekos (stew).', 'Luxury lodges and safari camps offer comfortable accommodations with views of the wilderness.', 'Embark on game drives to spot the Big Five (lion, elephant, buffalo, leopard, and rhinoceros), enjoy bush walks, and experience the magic of the African bush.'),
    ('Galápagos Islands, Ecuador', 'The Galápagos Islands are a volcanic archipelago in the Pacific Ocean, located about 1,000 kilometers (620 miles) west of Ecuador. They are renowned for their unique wildlife and pristine ecosystems.', 600, 0, '2024-03-12', 'Ecuadorian cuisine featuring fresh seafood, ceviche, and traditional dishes such as encebollado (fish soup) and llapingachos (potato patties).', 'Stay in eco-friendly lodges and boutique hotels on the islands.', 'Explore the islands diverse landscapes, observe endemic species such as giant tortoises, marine iguanas, and blue-footed boobies, and snorkel with sea lions and penguins.'),
    ('The Great Barrier Reef, Australia', 'The Great Barrier Reef is the worlds largest coral reef system, located off the coast of Queensland, Australia. Its renowned for its stunning marine biodiversity and vibrant coral reefs.', 500, 0, '2024-03-12', 'Australian cuisine featuring fresh seafood, grilled meats, and tropical fruits.', 'Stay in luxury resorts and eco-friendly lodges on the nearby islands or coastal towns.', 'Snorkel or dive among colorful coral gardens, swim with marine turtles, and explore the reefs diverse marine life on guided tours and excursions.'),
    ('Safari in Okavango Delta, Botswana', 'The Okavango Delta is a vast inland delta in northern Botswana, known for its sprawling grasslands, labyrinthine channels, and abundant wildlife. Its one of Africas premier safari destinations.', 600, 0, '2024-03-12', 'Traditional Botswana cuisine featuring game meats, samp (maize porridge), and seswaa (shredded beef).', 'Luxury tented camps and lodges offer accommodations with panoramic views of the delta.', 'Embark on game drives, mokoro (canoe) safaris, and guided walks to spot elephants, lions, hippos, and a variety of bird species.'),
    """

mycursor.execute(sql)

database.commit()

print(mycursor.rowcount, "record inserted.")
