# Generated by Django 5.0 on 2024-03-02 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='visited_by',
            field=models.ManyToManyField(blank=True, related_name='visited_attractions', to=settings.AUTH_USER_MODEL),
        ),
    ]
