# Generated by Django 5.0 on 2024-02-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='activity_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attraction',
            name='food_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='attraction',
            name='housing_description',
            field=models.TextField(default=''),
        ),
    ]
