# Generated by Django 5.0.2 on 2024-02-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="websiteuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="websiteuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="websiteuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
